### ISSUE TITLE
Serializer class causes issue saying User() has not attribute password2

### ISSUE THREAD

**Issue by Amitabh1989** [geekyshow1/djangoauthapi1#2]
**Issue Description :**
```
mysite_web  | Attributes are : OrderedDict([('password', 'root'), ('password2', 'root')])
mysite_web  | Internal Server Error: /auth/reset_password/
mysite_web  | Traceback (most recent call last):
mysite_web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 962, in create
mysite_web  |     instance = ModelClass._default_manager.create(**validated_data)
mysite_web  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mysite_web  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
mysite_web  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
mysite_web  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mysite_web  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 656, in create
mysite_web  |     obj = self.model(**kwargs)
mysite_web  |           ^^^^^^^^^^^^^^^^^^^^
mysite_web  |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 567, in __init__
mysite_web  |     raise TypeError(
mysite_web  | TypeError: User() got unexpected keyword arguments: 'password2'
mysite_web  |
mysite_web  | During handling of the above exception, another exception occurred:
```

**Comment by Amitabh1989** [comment]
To fix this issue, in serializer.py class, follow the below code :

```
    def validate(self, attrs):
        print(f"Attributes are : {attrs}")
        password = attrs.get("password")
        password2 = attrs.pop('password2')  <== Check this line. The description is below.
        if password != password2:
            raise serializers.ValidationError("Passwords do not match")
        user = self.context.get("user")
        print(f"User is : {user}")
        print(f"Returning attrs : {attrs}")
        return attrs
```

We are popping the value here because Password and Password2 are just used to validate that user has provided the same password as he intends to. Hence, we can safely pop the Password2 from the attrs. We later go on to save the password as needed.
